name: ci

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKER_BASE_NAME: ghcr.io/ksato9700/geth-exporter-rust

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container:
      image: "hadolint/hadolint:latest-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: hadolint ./Dockerfile

  main:
    runs-on: ubuntu-latest
    needs: hadolint
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . -t "${DOCKER_BASE_NAME}:latest"

      - run: docker images

      - name: Login to Registries
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "${GH_PAT}" | docker login ghcr.io -u peaceiris --password-stdin

      - name: Push to GitHub Container Repository (latest)
        run: docker push ${DOCKER_BASE_NAME}:latest

      - name: Push to GitHub Container Repository (release tag)
        if: github.event_name == 'release'
        run: |
          docker tag "${DOCKER_BASE_NAME}:latest" "${DOCKER_BASE_NAME}:${github.event.release.tag_name}"
          docker push "${DOCKER_BASE_NAME}:${github.event.release.tag_name}"
