name: ci

on:
  push:
    branches:
      - main

env:
  DOCKER_BASE_NAME: ghcr.io/ksato9700/geth-exporter-rust

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container:
      image: "hadolint/hadolint:latest-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: hadolint ./Dockerfile

  main:
    runs-on: ubuntu-latest
    needs: hadolint
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: |
          if [ "${{ github.event_name }}" = 'release' ]; then
              export TAG_NAME="${{ github.event.release.tag_name }}"
          else
              export TAG_NAME="latest"
          fi
          echo "PKG_TAG=${DOCKER_BASE_NAME}:${TAG_NAME}" >> ${GITHUB_ENV}

      - name: Build image
        run: |
          docker build . -t "${PKG_TAG}" --build-arg BASE_IMAGE="${{ matrix.baseimage }}"

      - run: docker images

      - name: Login to Registries
        if: github.event_name != 'pull_request'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "${GH_PAT}" | docker login ghcr.io -u peaceiris --password-stdin

      - name: Push to GitHub Packages
        if: github.event_name != 'pull_request'
        run: docker push "${PKG_TAG}"
